/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import DAO.LivroDAO;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

public class GeneralWindowVIEW extends javax.swing.JFrame {

    Boolean isBook, isHQ, isManga;
    Main main = new Main();
    public GeneralWindowVIEW() {
        initComponents();
        Manga.setBackground(new java.awt.Color(157, 188, 152));
        isManga = false;
        HQ.setBackground(new java.awt.Color(157, 188, 152));
        isHQ = false;

        Livro.setBackground(new java.awt.Color(99, 136, 137));
        SerieHQ.setEnabled(false);
        SerieHQ.setBackground(new java.awt.Color(235, 217, 180));
        VolumeHQManga.setEnabled(false);
        VolumeHQManga.setBackground(new java.awt.Color(235, 217, 180));
        isBook = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAbas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        JanelaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TituloLivro = new javax.swing.JTextField();
        SerieHQ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VolumeHQManga = new javax.swing.JTextField();
        AutorLivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        DiaCompra = new javax.swing.JTextField();
        MesCompra = new javax.swing.JTextField();
        AnoCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Manga = new javax.swing.JButton();
        Livro = new javax.swing.JButton();
        HQ = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BotaoMisterioso = new javax.swing.JButton();
        BotaoCadastrarLivros = new javax.swing.JButton();
        BotaoExibirColecao = new javax.swing.JButton();
        BotaoCriarEmprestimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JanelaCadastro.setBackground(new java.awt.Color(249, 239, 219));
        JanelaCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 136, 137));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Título");
        JanelaCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 243, 59, 28));

        TituloLivro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(TituloLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 244, 403, 28));

        SerieHQ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(SerieHQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 285, 403, 28));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(99, 136, 137));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Série");
        JanelaCadastro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 284, 59, 28));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 136, 137));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Volume");
        JanelaCadastro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 325, 59, 28));

        VolumeHQManga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(VolumeHQManga, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 326, 403, 28));

        AutorLivro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(AutorLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 367, 403, 28));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 136, 137));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Autor");
        JanelaCadastro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 366, 59, 28));

        Cadastrar.setBackground(new java.awt.Color(157, 188, 152));
        Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        JanelaCadastro.add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 220, 72));

        DiaCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(DiaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 407, 80, 28));

        MesCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(MesCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 407, 80, 28));

        AnoCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JanelaCadastro.add(AnoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 407, 80, 28));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 136, 137));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data");
        JanelaCadastro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 411, 59, -1));

        jLabel1.setBackground(new java.awt.Color(99, 136, 137));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 136, 137));
        jLabel1.setText("Cadastrar");
        JanelaCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 44, -1, -1));

        Manga.setBackground(new java.awt.Color(157, 188, 152));
        Manga.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Manga.setForeground(new java.awt.Color(255, 255, 255));
        Manga.setText("Mangá");
        Manga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangaActionPerformed(evt);
            }
        });
        JanelaCadastro.add(Manga, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 125, 148, 63));

        Livro.setBackground(new java.awt.Color(157, 188, 152));
        Livro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Livro.setForeground(new java.awt.Color(255, 255, 255));
        Livro.setText("Livro");
        Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivroActionPerformed(evt);
            }
        });
        JanelaCadastro.add(Livro, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 125, 148, 63));

        HQ.setBackground(new java.awt.Color(157, 188, 152));
        HQ.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HQ.setForeground(new java.awt.Color(255, 255, 255));
        HQ.setText("HQ");
        HQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HQActionPerformed(evt);
            }
        });
        JanelaCadastro.add(HQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 125, 148, 63));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JanelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(JanelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 97, Short.MAX_VALUE)))
        );

        painelAbas.addTab("Cadastrar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(249, 239, 219));

        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaLivros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        painelAbas.addTab("Listar todos os Livros", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );

        painelAbas.addTab("Emprestar Livro", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );

        painelAbas.addTab("Ver Empréstimos", jPanel4);

        getContentPane().add(painelAbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 0, 840, -1));
        painelAbas.getAccessibleContext().setAccessibleName("Cadastrar");

        BotaoMisterioso.setText("jButton1");
        BotaoMisterioso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(BotaoMisterioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 90));

        BotaoCadastrarLivros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoCadastrarLivros.setText("Cadastrar Livros");
        BotaoCadastrarLivros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoCadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarLivrosActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrarLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        BotaoExibirColecao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoExibirColecao.setText("Exibir Coleção");
        BotaoExibirColecao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoExibirColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExibirColecaoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoExibirColecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 90));

        BotaoCriarEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotaoCriarEmprestimo.setText("Criar Empréstimo");
        BotaoCriarEmprestimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoCriarEmprestimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCriarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCriarEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCriarEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        if(isBook) main.cadastrarLivro(TituloLivro.getText(), AutorLivro.getText(), Integer.parseInt(DiaCompra.getText()), Integer.parseInt(MesCompra.getText()), Integer.parseInt(AnoCompra.getText()));
        else if(isManga) main.cadastrarManga(TituloLivro.getText(), AutorLivro.getText(), Integer.parseInt(VolumeHQManga.getText()), Integer.parseInt(DiaCompra.getText()), Integer.parseInt(MesCompra.getText()), Integer.parseInt(AnoCompra.getText()));
        else if(isHQ) main.cadastrarHQ(TituloLivro.getText(), SerieHQ.getText(), AutorLivro.getText(), Integer.parseInt(VolumeHQManga.getText()), Integer.parseInt(DiaCompra.getText()), Integer.parseInt(MesCompra.getText()), Integer.parseInt(AnoCompra.getText()));
    }//GEN-LAST:event_CadastrarActionPerformed

    private void LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivroActionPerformed
        Manga.setBackground(new java.awt.Color(157, 188, 152));
        isManga = false;
        HQ.setBackground(new java.awt.Color(157, 188, 152));
        isHQ = false;

        Livro.setBackground(new java.awt.Color(99, 136, 137));
        SerieHQ.setEnabled(false);
        SerieHQ.setBackground(new java.awt.Color(235, 217, 180));
        SerieHQ.setText("");
        VolumeHQManga.setEnabled(false);
        VolumeHQManga.setBackground(new java.awt.Color(235, 217, 180));
        VolumeHQManga.setText("");
        isBook = true;
    }//GEN-LAST:event_LivroActionPerformed

    private void HQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HQActionPerformed
        Livro.setBackground(new java.awt.Color(157, 188, 152));
        isBook = false;
        Manga.setBackground(new java.awt.Color(157, 188, 152));
        isManga = false;

        HQ.setBackground(new java.awt.Color(99, 136, 137));
        SerieHQ.setEnabled(true);
        SerieHQ.setBackground(new java.awt.Color(249, 239, 219));
        VolumeHQManga.setEnabled(true);
        VolumeHQManga.setBackground(new java.awt.Color(249, 239, 219));
        isHQ = true;
    }//GEN-LAST:event_HQActionPerformed

    private void MangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangaActionPerformed
        Livro.setBackground(new java.awt.Color(157, 188, 152));
        isBook = false;
        HQ.setBackground(new java.awt.Color(157, 188, 152));
        isHQ = false;

        Manga.setBackground(new java.awt.Color(99, 136, 137));
        SerieHQ.setEnabled(false);
        SerieHQ.setBackground(new java.awt.Color(235, 217, 180));
        SerieHQ.setText("");
        VolumeHQManga.setEnabled(true);
        VolumeHQManga.setBackground(new java.awt.Color(249, 239, 219));
        isManga = true;
    }//GEN-LAST:event_MangaActionPerformed

    private DefaultTableModel LimpaTabela(DefaultTableModel tabela){
        tabela = null;
        return tabela;
    }
    
    private void BotaoExibirColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExibirColecaoActionPerformed
        tabelaLivros.setModel(new DefaultTableModel());
        painelAbas.setSelectedIndex(1);
        try{
        LivroDAO livroDAO = new LivroDAO();
        ResultSet rs = livroDAO.AcessarTabela();
        ResultSetMetaData rsmd = rs.getMetaData();
        DefaultTableModel model = (DefaultTableModel)tabelaLivros.getModel();
        int cols = rsmd.getColumnCount();
        String[] colName = new String[cols];
            for (int i = 0; i < cols; i++)
                colName[i] = rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            String id, titulo, serie, autor, volume, dataCompra;
            while(rs.next()){
                id = String.valueOf(rs.getString(1));
                titulo = rs.getString(2);
                serie = rs.getString(3);
                autor = rs.getString(4);
                volume = String.valueOf(rs.getInt(5));
                dataCompra = String.valueOf(rs.getDate(6));
                String[] row = {id, titulo, serie, autor, volume, dataCompra};
                model.addRow(row);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro GeneralWindowVIEW: " + ex.getMessage());
        }
    }//GEN-LAST:event_BotaoExibirColecaoActionPerformed

    private void BotaoCadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarLivrosActionPerformed
        painelAbas.setSelectedIndex(0);
    }//GEN-LAST:event_BotaoCadastrarLivrosActionPerformed

    private void BotaoCriarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCriarEmprestimoActionPerformed
        painelAbas.setSelectedIndex(2);
    }//GEN-LAST:event_BotaoCriarEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralWindowVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralWindowVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralWindowVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralWindowVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralWindowVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoCompra;
    private javax.swing.JTextField AutorLivro;
    private javax.swing.JButton BotaoCadastrarLivros;
    private javax.swing.JButton BotaoCriarEmprestimo;
    private javax.swing.JButton BotaoExibirColecao;
    private javax.swing.JButton BotaoMisterioso;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField DiaCompra;
    private javax.swing.JButton HQ;
    private javax.swing.JPanel JanelaCadastro;
    private javax.swing.JButton Livro;
    private javax.swing.JButton Manga;
    private javax.swing.JTextField MesCompra;
    private javax.swing.JTextField SerieHQ;
    private javax.swing.JTextField TituloLivro;
    private javax.swing.JTextField VolumeHQManga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painelAbas;
    private javax.swing.JTable tabelaLivros;
    // End of variables declaration//GEN-END:variables
}
